# Generated by Django 5.2.7 on 2025-10-28 18:12

from django.db import migrations, models
from django.utils.text import slugify


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_doctor_options_doctor_availability_doctor_bio_and_more'),
    ]

    def generate_slugs(apps, schema_editor):
        Doctor = apps.get_model('clinic', 'Doctor')

        for doctor in Doctor.objects.all():
            if doctor.slug:
                continue

            base_slug = slugify(doctor.name) or slugify(doctor.specialization) or 'doctor'
            slug_candidate = base_slug
            counter = 1

            while Doctor.objects.filter(slug=slug_candidate).exclude(pk=doctor.pk).exists():
                counter += 1
                slug_candidate = f"{base_slug}-{counter}"

            doctor.slug = slug_candidate
            doctor.save(update_fields=['slug'])

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.RunPython(generate_slugs, migrations.RunPython.noop),
    ]
